from indumentaria.dsl.components import Collar
from indumentaria.dsl.garment import Coat, Garment, load_garment


def test_garment_id_autogenerated(peacoat):
    assert isinstance(peacoat.garment_id, str) and len(peacoat.garment_id) > 0


def test_coat_full_has_no_missing_slots(peacoat):
    assert peacoat.missing_slots == []


def test_coat_reports_missing_slot_when_component_absent(peacoat):
    partial = peacoat.model_copy(
        update={"components": [c for c in peacoat.components if c.kind != "pocket"]}
    )
    assert partial.missing_slots == ["pocket"]


def test_serialization_roundtrip_preserves_component_subtypes(peacoat):
    data = peacoat.model_dump()
    restored = load_garment(data)
    assert isinstance(restored, Coat)
    collars = [c for c in restored.components if isinstance(c, Collar)]
    assert collars and collars[0].lapel_width_cm == 8.0
    assert restored == peacoat


def test_load_garment_dispatches_on_type(peacoat):
    assert isinstance(load_garment(peacoat.model_dump()), Coat)


def test_garment_id_unique_across_instances(peacoat):
    g1 = Coat(name="a", measurements=peacoat.measurements)
    g2 = Coat(name="b", measurements=peacoat.measurements)
    assert g1.garment_id != g2.garment_id


def test_load_garment_unknown_type_falls_back_to_base(peacoat):
    data = peacoat.model_dump()
    data["garment_type"] = "totally-unknown"
    restored = load_garment(data)
    assert type(restored) is Garment


def test_reference_image_round_trips():
    from indumentaria.dsl.garment import Garment, load_garment
    from indumentaria.dsl.measurements import BodyProfile, MeasurementSet

    g = Garment(
        name="x",
        measurements=MeasurementSet(body_profile=BodyProfile(measures={"chest_cm": 90.0})),
        reference_image="/assets/peacoat/reference.jpg",
    )
    restored = load_garment(g.model_dump())
    assert restored.reference_image == "/assets/peacoat/reference.jpg"


def test_build_peacoat_is_complete_coat():
    from indumentaria.dsl.examples import build_peacoat

    coat = build_peacoat()
    assert coat.garment_type == "coat"
    assert coat.missing_slots == []  # los 5 slots presentes
    assert {p.code for p in coat.measurements.poms} == {"A", "B"}
